### ISSUE TITLE
Unecessary long configuration for IPython

### ISSUE THREAD

**Issue by raffaem** [catppuccin/python#23]
The README [suggests](https://github.com/catppuccin/python#ipython) the following configuration for IPython:

```
from pygments.styles import get_style_by_name

c = get_config()
c.TerminalInteractiveShell.highlighting_style = get_style_by_name("catppuccin-mocha")
```

This doesn't seem necessary.

Just put:
```
c.TerminalInteractiveShell.highlighting_style = "catppuccin-mocha"
```
and it will work.

**Comment by backwardspy** [comment]
hey, thanks for raising this!

i have it that way in my config because it allows me to [gracefully handle](https://github.com/backwardspy/dots/blob/f6991570d6691212e27e266517656192f910ccbf/dot_config/ipython/profile_default/ipython_config.py#L8-L11) the theme not being installed rather than just crashing as it does if you use the name.

that said, i agree that our readme example should be as simple as possible (especially as it's labeled "minimum configuration") so if you wouldn't mind opening a PR i'd happily accept changing it to the one-liner you suggested.
