### ISSUE TITLE
Pygments syntax highlighting colors

### ISSUE THREAD

**Issue by uncenter** [catppuccin/python#72]
Raising this to track inaccuracies in syntax highlighting compared to our style guide and/or the VS Code / Neovim ports (commonly the authoritative source for syntax highlighting these days).

Section in question: https://github.com/catppuccin/python/blob/main/catppuccin/extras/pygments.py#L34-L115

I haven't had a chance to take a full look but you can see why I am raising this visually at https://github.com/catppuccin/userstyles/pull/1253#discussion_r1741124578.

**Comment by nikitarevenco** [comment]
Should I PR this? When theming https://github.com/catppuccin/userstyles/pull/1253 I effectively fixed a lot of issues with pygments highlighting

Topmost is my new version, the one on the bottom is the current one

![image](https://github.com/user-attachments/assets/5beb055c-acd1-4d85-8e46-8aa79167dc23)

**Comment by nikitarevenco** [comment]
https://learnxinyminutes.com is the perfect playground to fine-tune and test this, since they have all sorts of languages and are using pygments

**Comment by uncenter** [comment]
> Should I PR this? When theming https://github.com/catppuccin/userstyles/pull/1253 I effectively fixed a lot of issues with pygments highlighting

PR what though? You had classes in that userstyles PR and this uses named tokens.  If you are willing to spend the time figuring it out go ahead. I took a look earlier and it looked in order, seems like maybe an issue with subpar grammars and the current state being tailored to Python presumably.

**Comment by backwardspy** [comment]
the current pygments integration was very roughly based on the state of jetbrains and vscode as of nov 16, 2022. it wasn't entirely accurate and on top of that we've made quite a few changes the syntax colours since then so it's definitely in need of some TLC. pygments can be a pain to style because it's quite hard to find any actual documentation on it and it's also not the easiest thing to test.

i'd love a PR that either updates the colours to better fit the style guide and/or improves the testing story!
